### ISSUE TITLE
pgo-deploy playbook failed within ClusterRole definition (v4.3.0)

### ISSUE THREAD

**Issue by Fen0l** [CrunchyData/postgres-operator#1599]
**Which example are you working with?**
I am deploying postgres-operator through https://access.crunchydata.com/documentation/postgres-operator/4.3.0/quickstart/ (as images for 4.3.1 and 4.3.2 seems not ready yet) on a Kubernetes cluster with a single worker.

**What is the current behavior?**
I am having hard time deploying it. At the end of the pgo-deploy, the ansible playbook crash.
```
changed: true
cmd:
  - kubectl
  - create
  - '-f'
  - /tmp/.pgo/pgo/output/cluster-rbac.yaml
delta: '0:00:00.652867'
end: '2020-06-04 12:48:17.650495'
msg: non-zero r eturn code
rc: 1
start: '2020-06-04 12:48:16.997628'
stderr: >-
  Error from server (AlreadyExists): error when creating
  "/tmp/.pgo/pgo/output/cluster-rbac.yaml":
  clusterrolebindings.rbac.authorization .k8s.io "pgo-cluster-role" already
  exists
stderr_lines:
  - >-
    Error from server (AlreadyExists): error when creating
    "/tmp/.pgo/pgo/output/cluster-rbac.yaml":
    clusterrolebindings.rbac.authorization.k8s.io "pgo-cluster-role" already
    exists
stdout: clusterrole.rbac.authorization.k8s.io/pgo-cluster-role created
stdout_lines:
  - clusterrole.rbac.authorization.k8s.io/pgo-cluster-role created
```

I tried to delete everything, (roles, namespace) and retry to redeploy it but it always failed at this step.

**Other information** (e.g. detailed explanation, related issues,  etc)
This is my first time with PGO. I can see that pgo-cluster-role role exist.

**Please tell us about your environment:**

* Operating System: Centos 7
* Where is this running ( Local , Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): nfs
* Container Image Tag: v4.3.0
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift): Kubernetes
* Platform Version: v1.16.8
--

Logs:
```
➜  postgresql k logs --namespace pgo pgo-deploy-cqkdl

PLAY [Deploy Crunchy PostgreSQL Operator] **************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [pgo-preflight : fail] ****************************************************
skipping: [localhost]

TASK [pgo-preflight : Check Operating System] **********************************
changed: [localhost]

TASK [pgo-preflight : assert] **************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [pgo-preflight : assert] **************************************************
skipping: [localhost]

TASK [pgo-preflight : assert] **************************************************
skipping: [localhost]

TASK [pgo-preflight : assert] **************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [pgo-preflight : include_tasks] *******************************************
skipping: [localhost]

TASK [pgo-preflight : include_tasks] *******************************************
included: /ansible/roles/pgo-preflight/tasks/check_kubernetes.yml for localhost

TASK [pgo-preflight : Check if the kubectl command is installed] ***************
changed: [localhost]

TASK [pgo-preflight : Ensure kubectl is installed] *****************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [pgo-preflight : include_tasks] *******************************************
included: /ansible/roles/pgo-preflight/tasks/check_inventory.yml for localhost

TASK [pgo-preflight : Check if mandatory inventory file variables are defined] ***
skipping: [localhost] => (item=pgo_operator_namespace)
skipping: [localhost] => (item=pgo_installation_name)
skipping: [localhost] => (item=pgo_admin_username)
skipping: [localhost] => (item=pgo_admin_password)
skipping: [localhost] => (item=pgo_admin_role_name)
skipping: [localhost] => (item=pgo_admin_perms)
skipping: [localhost] => (item=ccp_image_prefix)
skipping: [localhost] => (item=ccp_image_tag)
skipping: [localhost] => (item=pgo_image_prefix)
skipping: [localhost] => (item=pgo_image_tag)
skipping: [localhost] => (item=disable_auto_failover)
skipping: [localhost] => (item=backrest)
skipping: [localhost] => (item=badger)
skipping: [localhost] => (item=metrics)
skipping: [localhost] => (item=archive_mode)
skipping: [localhost] => (item=archive_timeout)
skipping: [localhost] => (item=db_password_length)
skipping: [localhost] => (item=create_rbac)
skipping: [localhost] => (item=db_port)
skipping: [localhost] => (item=db_replicas)
skipping: [localhost] => (item=db_user)
skipping: [localhost] => (item=backrest_storage)
skipping: [localhost] => (item=backup_storage)
skipping: [localhost] => (item=primary_storage)
skipping: [localhost] => (item=replica_storage)
skipping: [localhost] => (item=pgo_client_version)
skipping: [localhost] => (item=pgbadgerport)
skipping: [localhost] => (item=exporterport)
skipping: [localhost] => (item=scheduler_timeout)
skipping: [localhost] => (item=namespace_mode)

TASK [pgo-operator : Set output directory fact] ********************************
ok: [localhost]

TASK [pgo-operator : Ensure output directory exists] ***************************
changed: [localhost]

TASK [pgo-operator : include_tasks] ********************************************
skipping: [localhost] => (item=openshift_auth.yml)
skipping: [localhost] => (item=openshift.yml)

TASK [pgo-operator : include_tasks] ********************************************
included: /ansible/roles/pgo-operator/tasks/kubernetes_auth.yml for localhost
included: /ansible/roles/pgo-operator/tasks/kubernetes.yml for localhost

TASK [pgo-operator : Set the Kubernetes Context] *******************************
skipping: [localhost]

TASK [pgo-operator : Get Namespace Details] ************************************
changed: [localhost]

TASK [pgo-operator : Create PGO Namespace] *************************************
skipping: [localhost]

TASK [pgo-operator : include_tasks] ********************************************
included: /ansible/roles/pgo-operator/tasks/certs.yml for localhost

TASK [pgo-operator : Ensure directory exists for local self-signed TLS certs.] ***
ok: [localhost]

TASK [pgo-operator : Generate RSA Key] *****************************************
changed: [localhost]

TASK [pgo-operator : Generate CSR] *********************************************
changed: [localhost]

TASK [pgo-operator : Generate Self-signed Certificate] *************************
changed: [localhost]

TASK [pgo-operator : Ensure /tmp/.pgo/pgo Directory Exists] ********************
ok: [localhost]

TASK [pgo-operator : Copy certificates to /tmp/.pgo/pgo] ***********************
changed: [localhost]

TASK [pgo-operator : Copy keys to /tmp/.pgo/pgo] *******************************
changed: [localhost]

TASK [pgo-operator : Use kubectl or oc] ****************************************
ok: [localhost]

TASK [pgo-operator : include_tasks] ********************************************
included: /ansible/roles/pgo-operator/tasks/namespace.yml for localhost

TASK [pgo-operator : Create Watched Namespaces] ********************************
changed: [localhost] => (item=pgo)

TASK [pgo-operator : include_tasks] ********************************************
included: /ansible/roles/pgo-operator/tasks/crds.yml for localhost

TASK [pgo-operator : Check if PGCluster CRD Is Installed] **********************
changed: [localhost]

TASK [pgo-operator : Create PGClusters CRD] ************************************
skipping: [localhost]

TASK [pgo-operator : Check if PGPolicies CRD Is Installed] *********************
changed: [localhost]

TASK [pgo-operator : Create PGPolicies CRD] ************************************
skipping: [localhost]

TASK [pgo-operator : Check if PGReplicas CRD Is Installed] *********************
changed: [localhost]

TASK [pgo-operator : Create PGReplicas CRD] ************************************
skipping: [localhost]

TASK [pgo-operator : Check if PGTasks CRD Is Installed] ************************
changed: [localhost]

TASK [pgo-operator : Create PGTasks CRD] ***************************************
skipping: [localhost]

TASK [pgo-operator : Template PGO Admin Credentials] ***************************
changed: [localhost]

TASK [pgo-operator : Create PGO Admin Credentials] *****************************
changed: [localhost]

TASK [pgo-operator : Template PGO Admin Role & Permissions] ********************
changed: [localhost]

TASK [pgo-operator : Create PGO Admin Role & Permissions] **********************
changed: [localhost]

TASK [pgo-operator : Template PGO Service Account] *****************************
changed: [localhost]

TASK [pgo-operator : Create PGO Service Account] *******************************
changed: [localhost]

TASK [pgo-operator : Template Cluster RBAC (namespace_mode 'dynamic')] *********
changed: [localhost]

TASK [pgo-operator : Create Cluster RBAC (namespace_mode 'dynamic')] ***********
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["kubectl", "create", "-f", "/tmp/.pgo/pgo/output/cluster-rbac.yaml"], "delta": "0:00:00.651608", "end": "2020-06-04 13:04:57.170767", "msg": "non-zero r
eturn code", "rc": 1, "start": "2020-06-04 13:04:56.519159", "stderr": "Error from server (AlreadyExists): error when creating \"/tmp/.pgo/pgo/output/cluster-rbac.yaml\": clusterrolebindings.rbac.authorization
.k8s.io \"pgo-cluster-role\" already exists", "stderr_lines": ["Error from server (AlreadyExists): error when creating \"/tmp/.pgo/pgo/output/cluster-rbac.yaml\": clusterrolebindings.rbac.authorization.k8s.io
\"pgo-cluster-role\" already exists"], "stdout": "clusterrole.rbac.authorization.k8s.io/pgo-cluster-role created", "stdout_lines": ["clusterrole.rbac.authorization.k8s.io/pgo-cluster-role created"]}

PLAY RECAP *********************************************************************
localhost                  : ok=36   changed=21   unreachable=0    failed=1    skipped=12   rescued=0    ignored=0
```

I only changed the password and the from the postgres-operator.yaml config file. (BACKREST_STORAGE, BACKUP_STORAGE, PRIMARY_STORAGE, REPLICA_STORAGE wthe nfsstorage val).

I have reviewed the yaml file with the only role declared is pgo-deployer-crb. May it come from the playbook who try to create it twice ?

Thank you for the help,

**Comment by jkatz** [comment]
This is fixed in #1502. In the absence of the newer containers (which are coming soon), I would suggest reading through the changes there: it's a matter of cleaning up the resources.

Thanks!

**Comment by Fen0l** [comment]
THank you @jkatz 

I just notice that v4.3.2 images were out. But even the problem is still here, i get an `Error from server (AlreadyExists): error when creating /tmp/.pgo/pgo/output/cluster-rbac.yaml`
