### ISSUE TITLE
archive_timeout

### ISSUE THREAD

**Issue by narayaana** [CrunchyData/postgres-operator#871]

**Comment by narayaana** [comment]
I try to change archive_timeout of postgresl.conf via pgo create cluster. I use backrest and default pgo clone. version 4.0.0. running on AKS.

I tried

--labels "archive_timeout=3600"
--labels "archive=true archive_timeout=3600"
--labels "archive=true"

--labels "archive-timeout=3600"
--labels "archive=true archive-timeout=3600"

none seem to affect the postgresql config 
at each installed an new "archive_timeout = 0"is appended to conf file instead of archive_timeout = 3600
my show cluster:

```
cluster : datascience-database-pitr (crunchy-postgres:centos7-11.3-2.4.0)
        pod : datascience-database-pitr-8dc9f8f97-9dc5z (Running) on aks-agentpool-28709018-4 (1/1) (primary)
        pvc : datascience-database-pitr
        pod : datascience-database-pitr-ltkq-75fd44b7f7-55xdj (Running) on aks-agentpool-28709018-4 (1/1) (replica)
        pvc : datascience-database-pitr-ltkq
        resources : CPU Limit= Memory Limit=, CPU Request= Memory Request=
        storage : Primary=40G Replica=40G
        deployment : datascience-database-pitr
        deployment : datascience-database-pitr-backrest-shared-repo
        deployment : datascience-database-pitr-ltkq
        service : datascience-database-pitr - ClusterIP (172.16.5.2)
        service : datascience-database-pitr-replica - ClusterIP (172.16.0.191)
        replica : datascience-database-pitr-ltkq
        labels : pg-cluster=datascience-database-pitr pgo-backrest=true current-primary=datascience-database-pitr deployment-name=datascience-database-pitr name=datascience-database-pitr crunchy_collect=false pgo-version=4.0.0 archive-timeout=3600 autofail=true crunchy-pgbadger=false

```

**Comment by cahoonpwork** [comment]
The --labels is just setting labels on the cluster that you can use selectors off of.  If you edit the pgo.yaml file for the following fields to:
ArchiveMode:  true
ArchiveTimeout:  3600

You will have to redeploy the operator for the configuration to be picked up.
Let us know if that works for you.

**Comment by narayaana** [comment]
it did not either. this is why I tried labels

**Comment by cahoonpwork** [comment]
We will look into it and see what is going on.

**Comment by cahoonpwork** [comment]
@narayaana looks like you found a bug.

**Comment by narayaana** [comment]
Ok, thanks for having looked into this. Will you post here if any fix is available ?

**Comment by cahoonpwork** [comment]
Yes, we will update this ticket when the fix is available.

**Comment by narayaana** [comment]
@cahoonpwork , any news regarding this one ?

**Comment by ajoyej** [comment]
@cahoonpwork: It seems that this issue is fixed with 4.1
We cannot reproduce it on our side.

Thanks,
José

**Comment by narayaana** [comment]
Still the same from 3 different browsers and 2 different OS.
[image: image.png]

**Comment by narayaana** [comment]
sorry, wrong destination
